"""Generate canonical Personal Auto standard, optional, and UW test data."""

import json
from copy import deepcopy
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
AUTO_DIR = ROOT / "testdata" / "static" / "auto"

CANONICAL_DEFAULTS = {
    "TC_ID": "",
    "TestName": "",
    "Description": "",
    "FlowType": "",
    "FieldsUnderTest": "",
    "ExpectedOutcome": "",
    "ExpectedTerminalState": "",
    "BindExpected": "",
    "UW_Rule": "",
    "UW_Description": "",
    "ExpectedUWType": "",
    "ExpectedCondition": "",
    "CustomerType": "Individual",
    "FirstName": "",
    "MiddleName": "",
    "LastName": "",
    "Prefix": "",
    "Suffix": "",
    "DOB": "",
    "SSN": "",
    "PhoneNum": "",
    "Email": "",
    "Address": "230 Old Taunton Ave",
    "Address2": "",
    "ZIP": "01101",
    "State": "Massachusetts",
    "City": "Springfield",
    "Country": "United States",
    "Agency": "Sherrie Insurance Co",
    "Producer": "Janis Irey",
    "Program": "Personal Auto",
    "EffectiveDate": "",
    "QuoteName": "",
    "Term": "12 Months",
    "ExpirationDate": "",
    "NetOfCommission": "",
    "CommissionBasis": "",
    "BillingMethod": "Direct Billed",
    "PriorCarrier": "",
    "PriorPolicyTerm": "",
    "PriorPolicyExpirationDate": "",
    "PriorPolicyPremium": "",
    "FalseInfo": "No",
    "DamageInfo": "No",
    "DescribeDamage": "",
    "Gender": "Male",
    "MaritalStatus": "Married",
    "RelationshipToInsured": "Self",
    "DriverStatus": "Active (rated)",
    "EmploymentCategory": "Employed",
    "Occupation": "Professional/Managerial",
    "LicenseStatus": "Active License",
    "CountryOfIssue": "United States",
    "LicenseState": "Massachusetts",
    "LicenseYear": "2010",
    "LicenseNumber": "",
    "LicensedAnotherState": "No",
    "SR22": "No",
    "SR22FilingState": "",
    "DefensiveDriver": "No",
    "FullTimeStudent": "No",
    "VehicleWithStudentAtSchool": "No",
    "GoodStudent": "No",
    "VehicleType": "Private Passenger Auto",
    "VehicleDetailEntryMode": "Use Lookup to Select VIN",
    "VIN": "",
    "Year": "2018",
    "Make": "BMW",
    "Model": "M3",
    "Spec": "Convertible 2-Door | 2WD | 4.0 Ltrs | 4x2",
    "VehicleUse": "Pleasure",
    "DistanceToWork": "",
    "Ownership": "Owned",
    "LossPayeeType": "",
    "LossPayeeName": "",
    "PhysicalDamageSymbol": "",
    "StatedAmount": "",
    "GaragingAddress1": "230 Old Taunton Ave",
    "GaragingAddress2": "",
    "GaragingCity": "Springfield",
    "GaragingState": "Massachusetts",
    "GaragingCountry": "United States",
    "GaragingZIP": "01101",
    "TitleJointlyOwned": "No",
    "PolicyCoverage": "Gold",
    "CompOTCOptions": "",
    "OTCDeductible": "",
    "CollisionDeductible": "",
    "Gap": "",
    "SoundEquipment": "",
    "CustomAmount": "",
    "Tapes": "",
    "SubstituteTransportation": "",
    "TransportationAndLaborLimit": "",
    "MedicalExpense": "",
    "WagesLossBasic": "",
    "FuneralExpense": "",
    "AccidentalDeath": "",
    "CombinationBase": "",
    "PayerCurrency": "US Dollar",
    "PaymentPlan": "Pay In Full",
    "nbCheck": "Processed",
}

PACKAGE_COVERAGES = {
    "Bronze": {
        "MedicalExpense": "10,000",
        "WagesLossBasic": "Max 5,000, Monthly 1,000",
        "FuneralExpense": "No Coverage",
        "AccidentalDeath": "No Coverage",
        "CombinationBase": "No",
        "OTCDeductible": "100",
        "CollisionDeductible": "100",
        "CompOTCOptions": "No Coverage",
        "TransportationAndLaborLimit": "No Coverage",
        "SubstituteTransportation": "50",
        "Gap": "No",
        "SoundEquipment": "1,500",
        "Tapes": "No Coverage",
        "CustomAmount": "1,500",
    },
    "Silver": {
        "MedicalExpense": "25,000",
        "WagesLossBasic": "Max 15,000, Monthly 1,000",
        "FuneralExpense": "No Coverage",
        "AccidentalDeath": "5,000",
        "CombinationBase": "No",
        "OTCDeductible": "250",
        "CollisionDeductible": "250",
        "CompOTCOptions": "No Coverage",
        "TransportationAndLaborLimit": "No Coverage",
        "SubstituteTransportation": "50",
        "Gap": "No",
        "SoundEquipment": "2,500",
        "Tapes": "No Coverage",
        "CustomAmount": "2,500",
    },
    "Gold": {
        "MedicalExpense": "50,000",
        "WagesLossBasic": "Max 25,000, Monthly 1,500",
        "FuneralExpense": "1,500",
        "AccidentalDeath": "10,000",
        "CombinationBase": "Yes",
        "OTCDeductible": "500",
        "CollisionDeductible": "500",
        "CompOTCOptions": "Full Glass",
        "TransportationAndLaborLimit": "25",
        "SubstituteTransportation": "50",
        "Gap": "Yes",
        "SoundEquipment": "3,500",
        "Tapes": "200",
        "CustomAmount": "3,500",
    },
    "Platinum": {
        "MedicalExpense": "100,000",
        "WagesLossBasic": "Max 50,000, Monthly 2,500",
        "FuneralExpense": "2,500",
        "AccidentalDeath": "25,000",
        "CombinationBase": "Yes",
        "OTCDeductible": "1,000",
        "CollisionDeductible": "1,000",
        "CompOTCOptions": "Full Glass",
        "TransportationAndLaborLimit": "25",
        "SubstituteTransportation": "50",
        "Gap": "Yes",
        "SoundEquipment": "5,000",
        "Tapes": "200",
        "CustomAmount": "5,000",
    },
}


def case(tc_id, test_name, flow_type, **overrides):
    record = deepcopy(CANONICAL_DEFAULTS)
    record.update(
        {
            "TC_ID": tc_id,
            "TestName": test_name,
            "Description": overrides.pop("Description", test_name),
            "FlowType": flow_type,
            "ExpectedOutcome": overrides.pop(
                "ExpectedOutcome",
                "Policy Bound" if flow_type != "uw" else "UW Referral",
            ),
            "ExpectedTerminalState": overrides.pop(
                "ExpectedTerminalState",
                "Policy Summary" if flow_type != "uw" else "UW Referral",
            ),
            "BindExpected": overrides.pop(
                "BindExpected",
                "No" if flow_type == "uw" else "Yes",
            ),
        }
    )
    record.update(overrides)
    record.update(PACKAGE_COVERAGES[record["PolicyCoverage"]])
    return record


def standard_cases():
    specs = [
        ("James", "Smith", "11/10/1992", "Male", "Married", "Pleasure", "Owned", "Gold"),
        ("Olivia", "Johnson", "05/12/1985", "Female", "Married", "Business", "Owned", "Silver"),
        ("Michael", "Williams", "08/22/1990", "Male", "Single", "Commute", "Owned", "Gold"),
        ("Sophia", "Brown", "12/01/1978", "Female", "Married", "Farm", "Owned", "Bronze"),
        ("David", "Jones", "03/15/1995", "Male", "Single", "Business", "Owned", "Platinum"),
        ("Emma", "Miller", "07/19/1982", "Female", "Married", "Commute", "Owned", "Gold"),
        ("Joseph", "Davis", "11/30/1988", "Male", "Married", "Farm", "Owned", "Silver"),
        ("Mia", "Wilson", "02/14/1991", "Female", "Single", "Pleasure", "Owned", "Gold"),
        ("Charles", "Rodriguez", "09/05/1965", "Male", "Married", "Business", "Owned", "Silver"),
        ("Ava", "Martinez", "06/18/1987", "Female", "Divorced", "Pleasure", "Owned", "Platinum"),
        ("Alan", "Carter", "03/15/1981", "Male", "Married", "Pleasure", "Leased", "Gold"),
        ("Grace", "Anderson", "04/09/1974", "Female", "Widowed", "Commute", "Financed", "Silver"),
        ("Henry", "Thomas", "10/26/1983", "Male", "Engaged", "Business", "Owned", "Bronze"),
        ("Chloe", "Taylor", "01/17/1994", "Female", "Single", "Commute", "Leased", "Platinum"),
        ("Daniel", "Moore", "07/07/1970", "Male", "Married", "Farm", "Financed", "Gold"),
        ("Lily", "Jackson", "09/23/1989", "Female", "Estranged", "Pleasure", "Owned", "Silver"),
        ("Matthew", "Martin", "11/02/1976", "Male", "Divorced", "Business", "Leased", "Bronze"),
        ("Nora", "Lee", "05/28/1993", "Female", "Married", "Commute", "Owned", "Platinum"),
        ("Samuel", "Perez", "08/11/1980", "Male", "Single", "Pleasure", "Financed", "Gold"),
        ("Ella", "Thompson", "12/19/1986", "Female", "Married", "Farm", "Owned", "Silver"),
    ]
    records = []
    for index, spec in enumerate(specs, start=1):
        first, last, dob, gender, marital, use, ownership, coverage = spec
        updates = {
            "FirstName": first,
            "LastName": last,
            "DOB": dob,
            "Gender": gender,
            "MaritalStatus": marital,
            "VehicleUse": use,
            "Ownership": ownership,
            "PolicyCoverage": coverage,
            "PhoneNum": f"413-555-{1000 + index:04d}",
            "Email": f"{first.lower()}.{last.lower()}_{{timestamp}}@auto.com",
            "LicenseNumber": f"MA{index:08d}",
            "DistanceToWork": "12" if use == "Commute" else "",
        }
        if ownership != "Owned":
            updates.update(
                {
                    "LossPayeeType": ownership,
                    "LossPayeeName": (
                        "BMW Financial Services"
                        if ownership == "Leased"
                        else "Massachusetts Auto Finance"
                    ),
                }
            )
        records.append(
            case(
                f"TC_ID_{index:04d}",
                f"Standard Auto flow {index:02d}: {use}, {ownership}, {coverage}",
                "standard",
                **updates,
            )
        )
    return records


def optional_cases():
    return [
        case(
            "AUTO_OPT_DRIVER_0001",
            "Driver identity fields",
            "optional",
            FirstName="Jordan",
            LastName="Parker",
            DOB="04/18/1988",
            Gender="Female",
            MaritalStatus="Single",
            Prefix="Ms.",
            MiddleName="L",
            SSN="234-56-7890",
            LicenseNumber="P23456789",
            Email="jparker_{timestamp}@auto.com",
            FieldsUnderTest="Prefix, MiddleName, RelationshipToInsured, SSN",
        ),
        case(
            "AUTO_OPT_VEHICLE_0001",
            "Leased vehicle, loss payee, and physical damage symbol",
            "optional",
            FirstName="Taylor",
            LastName="Morgan",
            DOB="08/22/1979",
            Prefix="Mr.",
            LicenseNumber="M34567890",
            Ownership="Leased",
            LossPayeeType="Leased",
            LossPayeeName="Springfield Leasing Co",
            PhysicalDamageSymbol="1",
            Email="tmorgan_{timestamp}@auto.com",
            FieldsUnderTest=(
                "Ownership, LossPayeeType, LossPayeeName, PhysicalDamageSymbol"
            ),
        ),
        case(
            "AUTO_OPT_DRIVER_0002",
            "Driver suffix and retired employment",
            "optional",
            FirstName="Robert",
            LastName="Hall",
            DOB="01/21/1958",
            Prefix="Dr.",
            MiddleName="A",
            Suffix="Jr.",
            EmploymentCategory="Retired",
            Occupation="Health Care",
            LicenseYear="1978",
            LicenseNumber="H22004567",
            DefensiveDriver="Yes",
            Email="rhall_{timestamp}@auto.com",
            FieldsUnderTest=(
                "Prefix, MiddleName, Suffix, EmploymentCategory, Occupation, "
                "LicenseYear, DefensiveDriver"
            ),
        ),
        case(
            "AUTO_OPT_DRIVER_0003",
            "Unemployed driver with prior-state license response",
            "optional",
            FirstName="Monica",
            LastName="Green",
            DOB="03/12/1984",
            Gender="Female",
            MaritalStatus="Divorced",
            Prefix="Mrs.",
            EmploymentCategory="Unemployed",
            Occupation="Homemaker",
            LicensedAnotherState="Yes",
            LicenseNumber="G77331122",
            Email="mgreen_{timestamp}@auto.com",
            FieldsUnderTest=(
                "Prefix, EmploymentCategory, Occupation, LicensedAnotherState"
            ),
        ),
        case(
            "AUTO_OPT_DRIVER_0004",
            "Disabled driver and defensive course",
            "optional",
            FirstName="Peter",
            LastName="Young",
            DOB="06/30/1972",
            EmploymentCategory="Disabled",
            Occupation="Non Profit/Volunteer",
            DefensiveDriver="Yes",
            LicenseNumber="Y66009871",
            Email="pyoung_{timestamp}@auto.com",
            FieldsUnderTest="EmploymentCategory, Occupation, DefensiveDriver",
        ),
        case(
            "AUTO_OPT_QUOTE_0001",
            "Agency billing with commission fields",
            "optional",
            FirstName="Rachel",
            LastName="King",
            DOB="09/16/1981",
            Gender="Female",
            BillingMethod="Agency Billed",
            NetOfCommission="Net commission",
            CommissionBasis="Commission",
            QuoteName="Agency billed optional quote",
            LicenseNumber="K88224461",
            Email="rking_{timestamp}@auto.com",
            FieldsUnderTest=(
                "QuoteName, BillingMethod, NetOfCommission, CommissionBasis"
            ),
        ),
        case(
            "AUTO_OPT_QUOTE_0002",
            "Prior carrier and prior premium fields",
            "optional",
            FirstName="Steven",
            LastName="Wright",
            DOB="12/08/1977",
            PriorCarrier="Travelers",
            PriorPolicyTerm="12 Months",
            PriorPolicyExpirationDate="06/01/2026",
            PriorPolicyPremium="1450",
            LicenseNumber="W11997731",
            Email="swright_{timestamp}@auto.com",
            FieldsUnderTest=(
                "PriorCarrier, PriorPolicyTerm, PriorPolicyExpirationDate, "
                "PriorPolicyPremium"
            ),
        ),
        case(
            "AUTO_OPT_DAMAGE_0001",
            "Existing vehicle damage description",
            "optional",
            FirstName="Laura",
            LastName="Scott",
            DOB="05/05/1986",
            Gender="Female",
            DamageInfo="Yes",
            DescribeDamage="Minor cosmetic scratch on rear passenger door",
            LicenseNumber="S55442219",
            Email="lscott_{timestamp}@auto.com",
            FieldsUnderTest="DamageInfo, DescribeDamage",
        ),
        case(
            "AUTO_OPT_VEHICLE_0002",
            "Financed vehicle with loss payee",
            "optional",
            FirstName="Brian",
            LastName="Adams",
            DOB="02/24/1980",
            Ownership="Financed",
            LossPayeeType="Financed",
            LossPayeeName="Massachusetts Auto Finance",
            LicenseNumber="A44007612",
            Email="badams_{timestamp}@auto.com",
            FieldsUnderTest="Ownership, LossPayeeType, LossPayeeName",
        ),
        case(
            "AUTO_OPT_VEHICLE_0003",
            "Jointly owned vehicle title",
            "optional",
            FirstName="Diana",
            LastName="Baker",
            DOB="07/14/1983",
            Gender="Female",
            TitleJointlyOwned="Yes",
            LicenseNumber="B33118890",
            Email="dbaker_{timestamp}@auto.com",
            FieldsUnderTest="TitleJointlyOwned",
        ),
        case(
            "AUTO_OPT_VEHICLE_0004",
            "Business-use vehicle with physical damage override",
            "optional",
            FirstName="Kevin",
            LastName="Nelson",
            DOB="10/10/1975",
            VehicleUse="Business",
            PhysicalDamageSymbol="2",
            PolicyCoverage="Platinum",
            LicenseNumber="N66221100",
            Email="knelson_{timestamp}@auto.com",
            FieldsUnderTest=(
                "VehicleUse, PhysicalDamageSymbol, PolicyCoverage, "
                "PackageDerivedCoverages"
            ),
        ),
        case(
            "AUTO_OPT_VEHICLE_0005",
            "Commute vehicle with distance-to-work data",
            "optional",
            FirstName="Amy",
            LastName="Hill",
            DOB="04/03/1990",
            Gender="Female",
            VehicleUse="Commute",
            DistanceToWork="25",
            PolicyCoverage="Silver",
            LicenseNumber="H99553318",
            Email="ahill_{timestamp}@auto.com",
            FieldsUnderTest="VehicleUse, DistanceToWork, PolicyCoverage",
        ),
        case(
            "AUTO_OPT_DRIVER_0005",
            "SR-22 driver with filing state",
            "uw",
            Description=(
                "SR-22 required driver with conditional SR-22 Filing State set "
                "to New York; stops at UW referral"
            ),
            ExpectedOutcome="UW Referral",
            ExpectedTerminalState="UW Referral",
            BindExpected="No",
            ExpectedUWType="Underwriting",
            ExpectedCondition=(
                "SR-22 / Certificate of Insurance Indicator is checked"
            ),
            FirstName="Victor",
            LastName="Cruz",
            DOB="08/14/1985",
            MaritalStatus="Single",
            LicenseNumber="C77114422",
            SR22="Yes",
            SR22FilingState="New York",
            Email="vcruz_{timestamp}@auto.com",
            FieldsUnderTest="SR22, SR22FilingState",
        ),
        case(
            "AUTO_OPT_VEHICLE_0006",
            "Garaging address matches customer address",
            "optional",
            Description=(
                "Confirms inherited garaging fields match the customer address "
                "and remain read-only"
            ),
            FirstName="Sandra",
            LastName="Rivera",
            DOB="11/22/1979",
            Gender="Female",
            LicenseNumber="R12345678",
            Email="srivera_{timestamp}@auto.com",
            FieldsUnderTest=(
                "GaragingAddress1, GaragingCity, GaragingState, GaragingZIP"
            ),
        ),
        case(
            "AUTO_FLOW_E2E_0001",
            "Combined compatible optional fields",
            "optional",
            Description=(
                "Covers quote, driver, vehicle, loss-payee, commute, and "
                "package-derived coverage fields in one bindable E2E flow"
            ),
            FirstName="Cameron",
            MiddleName="J",
            LastName="Reed",
            Prefix="Mr.",
            DOB="02/12/1984",
            MaritalStatus="Married",
            QuoteName="Combined optional E2E flow",
            BillingMethod="Agency Billed",
            NetOfCommission="Net commission",
            CommissionBasis="Commission",
            PriorCarrier="Travelers",
            PriorPolicyTerm="12 Months",
            PriorPolicyExpirationDate="06/01/2026",
            PriorPolicyPremium="1650",
            RelationshipToInsured="Self",
            EmploymentCategory="Employed",
            Occupation="Professional/Managerial",
            DefensiveDriver="Yes",
            LicenseNumber="R24681357",
            VehicleUse="Commute",
            DistanceToWork="18",
            Ownership="Leased",
            LossPayeeType="Leased",
            LossPayeeName="BMW Financial Services",
            PhysicalDamageSymbol="1",
            TitleJointlyOwned="Yes",
            PolicyCoverage="Platinum",
            Email="creed_{timestamp}@auto.com",
            FieldsUnderTest=(
                "QuoteName, BillingMethod, NetOfCommission, CommissionBasis, "
                "PriorCarrier, PriorPolicyTerm, PriorPolicyExpirationDate, "
                "PriorPolicyPremium, Prefix, MiddleName, RelationshipToInsured, "
                "EmploymentCategory, Occupation, DefensiveDriver, VehicleUse, "
                "DistanceToWork, Ownership, LossPayeeType, LossPayeeName, "
                "PhysicalDamageSymbol, TitleJointlyOwned, PolicyCoverage, "
                "PackageDerivedCoverages"
            ),
        ),
    ]


def uw_cases():
    base = {
        "ExpectedOutcome": "UW Referral",
        "ExpectedUWType": "Underwriting",
    }
    return [
        case(
            "UW_TC_001",
            "SR-22 only",
            "uw",
            **base,
            UW_Rule="SR-22 Only",
            UW_Description="Adult active driver requiring SR-22",
            ExpectedCondition="SR-22 / Certificate of Insurance Indicator is checked",
            FieldsUnderTest="SR22, SR22FilingState",
            FirstName="Tyler",
            LastName="Hendricks",
            DOB="06/15/1993",
            MaritalStatus="Single",
            SR22="Yes",
            SR22FilingState="Massachusetts",
            LicenseNumber="H10000001",
            Email="thendricks_{timestamp}@uwtest.com",
        ),
        case(
            "UW_TC_002",
            "Suspended license only",
            "uw",
            **base,
            UW_Rule="Suspended License Only",
            UW_Description="Adult driver with suspended license",
            ExpectedCondition="driver license status that is revoked or suspended",
            FieldsUnderTest="LicenseStatus",
            FirstName="Brandon",
            LastName="Kelley",
            DOB="03/22/1987",
            LicenseStatus="Suspended",
            LicenseNumber="K10000002",
            Email="bkelley_{timestamp}@uwtest.com",
        ),
        case(
            "UW_TC_003",
            "Young driver under 25",
            "uw",
            **base,
            UW_Rule="Young Driver Under 25",
            UW_Description="Twenty-one-year-old active driver",
            ExpectedCondition="All drivers under 25 years of age",
            FieldsUnderTest="DOB",
            FirstName="Marcus",
            LastName="Crawford",
            DOB="08/14/2004",
            MaritalStatus="Single",
            EmploymentCategory="Employed",
            LicenseYear="2021",
            LicenseNumber="C10000003",
            VehicleUse="Commute",
            DistanceToWork="10",
            Email="mcrawford_{timestamp}@uwtest.com",
        ),
        case(
            "UW_TC_004",
            "Revoked license only",
            "uw",
            **base,
            UW_Rule="Revoked License Only",
            UW_Description="Adult driver with revoked license",
            ExpectedCondition="driver license status that is revoked or suspended",
            FieldsUnderTest="LicenseStatus",
            FirstName="Derek",
            LastName="Patterson",
            DOB="11/05/1990",
            MaritalStatus="Single",
            LicenseStatus="Revoked",
            LicenseNumber="P10000004",
            PolicyCoverage="Bronze",
            Email="dpatterson_{timestamp}@uwtest.com",
        ),
        case(
            "UW_TC_005",
            "SR-22 and under 25",
            "uw",
            **base,
            UW_Rule="SR-22 + Under 25",
            UW_Description="Young active driver requiring SR-22",
            ExpectedCondition=(
                "SR-22 / Certificate of Insurance Indicator is checked; "
                "All drivers under 25 years of age"
            ),
            FieldsUnderTest="DOB, SR22, SR22FilingState",
            FirstName="Ethan",
            LastName="Morrison",
            DOB="03/28/2006",
            MaritalStatus="Single",
            SR22="Yes",
            SR22FilingState="Massachusetts",
            LicenseYear="2023",
            LicenseNumber="M10000005",
            VehicleUse="Business",
            PolicyCoverage="Platinum",
            Email="emorrison_{timestamp}@uwtest.com",
        ),
        case(
            "UW_TC_006",
            "SR-22 and suspended license",
            "uw",
            **base,
            UW_Rule="SR-22 + Suspended License",
            UW_Description="Adult driver with SR-22 and suspended license",
            ExpectedCondition="driver license status that is revoked or suspended",
            FieldsUnderTest="SR22, SR22FilingState, LicenseStatus",
            FirstName="Harold",
            LastName="Whitfield",
            DOB="03/28/1988",
            SR22="Yes",
            SR22FilingState="Massachusetts",
            LicenseStatus="Suspended",
            LicenseNumber="W10000006",
            Email="hwhitfield_{timestamp}@uwtest.com",
        ),
        case(
            "UW_TC_007",
            "Triple risk SR-22, revoked, under 25",
            "uw",
            **base,
            UW_Rule="SR-22 + Revoked + Under 25",
            UW_Description="Young revoked driver requiring SR-22",
            ExpectedCondition="SR-22 / Certificate of Insurance Indicator is checked",
            FieldsUnderTest=(
                "DOB, SR22, SR22FilingState, LicenseStatus, DamageInfo, "
                "DescribeDamage"
            ),
            FirstName="Victor",
            LastName="Sloane",
            DOB="09/19/2003",
            MaritalStatus="Single",
            SR22="Yes",
            SR22FilingState="Massachusetts",
            LicenseStatus="Revoked",
            LicenseYear="2020",
            LicenseNumber="S10000007",
            DamageInfo="Yes",
            DescribeDamage="Rear bumper and trunk damage from prior collision",
            VehicleUse="Business",
            PolicyCoverage="Platinum",
            Email="vsloane_{timestamp}@uwtest.com",
        ),
        case(
            "UW_TC_008",
            "Under 25 with leased vehicle",
            "uw",
            **base,
            UW_Rule="Under 25 + Leased Vehicle",
            UW_Description="Young driver with leased BMW",
            ExpectedCondition="All drivers under 25 years of age",
            FieldsUnderTest="DOB, Ownership, LossPayeeType, LossPayeeName",
            FirstName="Nathan",
            LastName="Fielding",
            DOB="05/30/2003",
            MaritalStatus="Single",
            LicenseYear="2020",
            LicenseNumber="F10000008",
            VehicleUse="Commute",
            DistanceToWork="18",
            Ownership="Leased",
            LossPayeeType="Leased",
            LossPayeeName="BMW Financial Services",
            Email="nfielding_{timestamp}@uwtest.com",
        ),
        case(
            "UW_TC_009",
            "Under 25 with suspended license",
            "uw",
            **base,
            UW_Rule="Under 25 + Suspended License",
            UW_Description="Young driver with suspended license",
            ExpectedCondition="driver license status that is revoked or suspended",
            FieldsUnderTest="DOB, LicenseStatus",
            FirstName="Gregory",
            LastName="Ashford",
            DOB="07/11/2003",
            MaritalStatus="Single",
            LicenseStatus="Suspended",
            LicenseYear="2020",
            LicenseNumber="A10000009",
            VehicleUse="Commute",
            DistanceToWork="8",
            Email="gashford_{timestamp}@uwtest.com",
        ),
        case(
            "UW_TC_010",
            "SR-22 with leased vehicle",
            "uw",
            **base,
            UW_Rule="SR-22 + Leased Vehicle",
            UW_Description="Adult SR-22 driver with leased BMW",
            ExpectedCondition="SR-22 / Certificate of Insurance Indicator is checked",
            FieldsUnderTest=(
                "SR22, SR22FilingState, Ownership, LossPayeeType, LossPayeeName"
            ),
            FirstName="Calvin",
            LastName="Monroe",
            DOB="02/17/1991",
            MaritalStatus="Single",
            SR22="Yes",
            SR22FilingState="Massachusetts",
            LicenseNumber="M10000010",
            VehicleUse="Commute",
            DistanceToWork="15",
            Ownership="Leased",
            LossPayeeType="Leased",
            LossPayeeName="BMW Financial Services",
            Email="cmonroe_{timestamp}@uwtest.com",
        ),
    ]


def write_json(path, records):
    path.write_text(
        json.dumps({"testCases": records}, indent=2) + "\n",
        encoding="utf-8",
    )


def main():
    standard = standard_cases()
    optional = optional_cases()
    underwriting = uw_cases()
    write_json(AUTO_DIR / "AutoData.json", standard + optional)
    write_json(AUTO_DIR / "AutoUWRulesData.json", underwriting)
    print(
        f"Wrote {len(standard)} standard + {len(optional)} optional cases "
        f"and {len(underwriting)} UW cases."
    )


if __name__ == "__main__":
    main()
